### ISSUE TITLE
Approachable Documentation

### ISSUE THREAD

**Issue by Plecra** [Inky-developer/debris#1]
This looks really cool! I've been wanting a language like this to keep datapacks from being such a chore to write.

I imagine more contributors would be quite helpful for a project like this, but I'm not sure what your plans are, or where you'd like help. I've got a couple ideas that might help, but I'm sure there's much more that can be done!

## Code documentation

Set up your CI to push the documentation to GitHub pages. This will make it easier to what's going on "now" (documentation staying up to date with code is just *great*), and especially what needs doing.

- Ideally, you could also configure rustdoc to link to versioned source on github.
- Move the explanations in the READMEs into the code, where you can link directly to the types when referring to them.

## Syntax

An EBNF grammar would serve as a good introduction to the goals and status of the project - you could quickly find the work that needs doing by finding the syntax rule you want implemented.

> I see you're using a pest grammar for the parsing. That's nice, though it makes the language harder to understand for people who don't use pest (or more generally, Rust)

**Comment by Inky-developer** [comment]
In my opinion the pest grammar is quite readable since it does not differ much from the EBNF form. 
Unfortunately, I don't have a complete 'vision' for what the finished langauge should look like. From my experimentation I found that a language that compiles to minecraft can be much more powerful than initially thought. 
Syntax-wise, the language should be similar to the prototype that is linked in the readme.
Currently, the plan is to get the language to a similar level of the prototype, which supports functions, conditions, loops, structs and very basic types. As of right now, almost everything of this ist yet to be implemented. 

After that, the main priorities are implementing a good standard library and implementing language support for async code.

**Comment by Inky-developer** [comment]
I have set up online documentation [here](https://inky-developer.github.io/debris/debris_lang/). The page is also linked in the Readme.

If you've got any questions, feel free to message me!
