### ISSUE TITLE
Formatted strings

### ISSUE THREAD

**Issue by Plecra** [Inky-developer/debris#4]
> The `timer.mcscript` example
```
tickCount = 0

fun on_tick() {
    run for @a at @s {
        if tickCount % 20 == 0 {
            actionbar("{} Second: {}", @s, tickCount / 20)
        }
    }
    tickCount += 1
}
```
`actionbar("{} Second: {}", @s, tickCount / 20)`

Is there a reason you've decided to embed the formatting syntax into each individual function? I think a string interpolation syntax would be much nicer if it's possible.

**Comment by Inky-developer** [comment]
First of all: Thank you for taking a look at this project, even though it is still in very early development!

I totally agree that string interpolation would be great to have supported but a big technical problem is that string interpolation cannot return a value of type string.
By this I mean that a string like `"Hello world" `should have the same type as `"Hello {@s}"`, but this is not possible because the formatted string looks internally something like `[{"text":"Hello "}, {"selector":"@s"}]`. 
I think it goes against intuition that quoted text can either be of type string or type json, depending on what they look like.
An alternative would be something like a `format_json(literal, args...)` function, but `actionbar(format_json("Hello {}", @s))` does not look very nice.

Because of that I don't think it is an easy decision whether to add string interpolation, and I am not sure yet which is the best way to go.

**Comment by Plecra** [comment]
How about JavaScript's `` `Hello {@s}` `` or Python's `f"Hello {@s}"`? I think it's best to lean into them being different types and just use different syntax

**Comment by Inky-developer** [comment]
That seems like a nice idea

**Comment by Inky-developer** [comment]
Initial implementation in commit 1c2178c4cbf49f124316c000e64d1f5efa861f21
